[package]
name = "rtex"
version = "0.1.0"
edition = "2021"
autobins = false
default-run = "pratex"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
debug = 2

[features]
default = ["stats"]

# Enables statistics
stats = []

# For TRIP testing
trip = ["stats"]

[dependencies]
vaak = { path = "../vaak" }
chrono = { version = "0.4.45", default-features = false, features = ["std"] }

[target.'cfg(any(unix, windows))'.dependencies]
chrono = { version = "0.4.45", default-features = false, features = ["clock"] }

[[bin]]
name = "pratex"
path = "src/main.rs"

[[bin]]
name = "rtex"
path = "src/bin/rtex.rs"
