#!/usr/bin/env bash

# Compare PraTeX, upLaTeX, and LuaLaTeX sequentially on one CPU.  PraTeX and
# upLaTeX must produce byte-identical or canonically equivalent DVI.
# LuaLaTeX remains a separate workload column because its format, font path,
# and DVI records are not the same compatibility oracle.

set -euo pipefail

for command_name in awk basename cp dirname env find grep install kpsewhich mkdir mktemp perf python3 readlink sha256sum sort tail taskset time wc; do
    command -v "$command_name" >/dev/null || {
        printf 'required command is missing: %s\n' "$command_name" >&2
        exit 1
    }
done

repo_root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
pratex_source=${PRATEX_DOCUMENT_BINARY:?set PRATEX_DOCUMENT_BINARY to a release PraTeX executable}
format_source=${PRATEX_DOCUMENT_FORMAT:?set PRATEX_DOCUMENT_FORMAT to latex.fmt generated by that executable}
uplatex_source=${UPLATEX_DOCUMENT_BINARY:-$(command -v uplatex)}
lualatex_source=${LUALATEX_DOCUMENT_BINARY:-$(command -v lualatex)}
runs=${PRATEX_DOCUMENT_RUNS:-7}
warmups=${PRATEX_DOCUMENT_WARMUPS:-3}
cpu=${PRATEX_DOCUMENT_CPU:-0}
source_date_epoch=${SOURCE_DATE_EPOCH:-1709210096}
output_comment=PraTeX-document-bench

case "$runs" in
    '' | *[!0-9]* | 0)
        printf 'PRATEX_DOCUMENT_RUNS must be a positive integer: %s\n' "$runs" >&2
        exit 1
        ;;
esac
case "$warmups" in
    '' | *[!0-9]*)
        printf 'PRATEX_DOCUMENT_WARMUPS must be a non-negative integer: %s\n' "$warmups" >&2
        exit 1
        ;;
esac
case "$cpu" in
    '' | *[!0-9]*)
        printf 'PRATEX_DOCUMENT_CPU must be a non-negative integer: %s\n' "$cpu" >&2
        exit 1
        ;;
esac

test -x "$pratex_source" || {
    printf 'PraTeX executable is missing: %s\n' "$pratex_source" >&2
    exit 1
}
test -f "$format_source" || {
    printf 'PraTeX format is missing: %s\n' "$format_source" >&2
    exit 1
}
test -x "$uplatex_source" || {
    printf 'upLaTeX executable is missing: %s\n' "$uplatex_source" >&2
    exit 1
}
test -x "$lualatex_source" || {
    printf 'LuaLaTeX executable is missing: %s\n' "$lualatex_source" >&2
    exit 1
}

if test "$#" -eq 0; then
    set -- "$repo_root/tools/fixtures/lipsum-300page.tex"
fi
for fixture in "$@"; do
    test -f "$fixture" || {
        printf 'fixture is missing: %s\n' "$fixture" >&2
        exit 1
    }
done

if test -n "${PRATEX_DOCUMENT_WORK_ROOT:-}"; then
    work_root=$PRATEX_DOCUMENT_WORK_ROOT
    mkdir -p "$work_root"
    if test "$(find "$work_root" -mindepth 1 -maxdepth 1 | wc -l)" -ne 0; then
        printf 'PRATEX_DOCUMENT_WORK_ROOT must be empty: %s\n' "$work_root" >&2
        exit 1
    fi
else
    work_root=$(mktemp -d "${TMPDIR:-/tmp}/pratex-document-bench.XXXXXXXX")
fi

pratex_dir=$work_root/pratex
uplatex_dir=$work_root/uplatex
lualatex_dir=$work_root/lualatex
lua_cache=$work_root/lua-cache
result_dir=$work_root/result
bin_dir=$work_root/bin
mkdir -p "$pratex_dir" "$uplatex_dir" "$lualatex_dir" "$lua_cache" "$result_dir" "$bin_dir"
printf 'pratex-document-bench-v2\n' >"$work_root/.pratex-document-bench-v2"

# Copy executables and the format before measurement so concurrent builds do
# not change a running benchmark.
install -m 755 "$pratex_source" "$bin_dir/pratex"
pratex=$bin_dir/pratex
uplatex=$uplatex_source
lualatex=$lualatex_source
uplatex_resolved=$(readlink -f -- "$uplatex_source")
lualatex_resolved=$(readlink -f -- "$lualatex_source")
cp -- "$format_source" "$pratex_dir/latex.fmt"

fixture_ids=()
for fixture in "$@"; do
    fixture_id=$(basename -- "$fixture" .tex)
    for known_id in "${fixture_ids[@]:-}"; do
        test "$fixture_id" != "$known_id" || {
            printf 'fixture basenames must be unique: %s\n' "$fixture_id" >&2
            exit 1
        }
    done
    fixture_ids+=("$fixture_id")
    cp -- "$fixture" "$pratex_dir/$fixture_id.tex"
    cp -- "$fixture" "$uplatex_dir/$fixture_id.tex"
    cp -- "$fixture" "$lualatex_dir/$fixture_id.tex"
done

texmf_root=$(kpsewhich -var-value=TEXMFROOT)
texmf_dist=$(kpsewhich -var-value=TEXMFDIST)
texmf_local=$(kpsewhich -var-value=TEXMFLOCAL)
texmf_sysvar=$(kpsewhich -var-value=TEXMFSYSVAR)
texmf_sysconfig=$(kpsewhich -var-value=TEXMFSYSCONFIG)
texmf_cnf=$texmf_dist/web2c
for required_path in "$texmf_root" "$texmf_dist" "$texmf_sysvar" "$texmf_sysconfig" "$texmf_cnf"; do
    test -d "$required_path" || {
        printf 'TeX Live path is missing: %s\n' "$required_path" >&2
        exit 1
    }
done

common_env=(
    "SOURCE_DATE_EPOCH=$source_date_epoch"
    "TEXMFROOT=$texmf_root"
    "TEXMFDIST=$texmf_dist"
    "TEXMFLOCAL=$texmf_local"
    "TEXMFSYSVAR=$texmf_sysvar"
    "TEXMFSYSCONFIG=$texmf_sysconfig"
    "TEXMFVAR=$texmf_sysvar"
    "TEXMFCONFIG=$texmf_sysconfig"
    "TEXMFCNF=$texmf_cnf"
)
lua_env=(
    "SOURCE_DATE_EPOCH=$source_date_epoch"
    "TEXMFCACHE=$lua_cache"
    "TEXMFVAR=$lua_cache"
)

printf 'engine\tfixture\tround\twall_ns\twall_s\tuser_s\tsys_s\tpeak_rss_kb\n' >"$result_dir/runs.tsv"
printf 'engine\tfixture\tround\tdvi_sha256\tdvi_bytes\n' >"$result_dir/dvi.tsv"
printf 'engine\tfixture\tround\tfile\tsha256\tbytes\n' >"$result_dir/support-files.tsv"
printf 'fixture\tcomparison\tevidence_sha256\n' >"$result_dir/dvi-meaning.tsv"

run_engine() {
    local engine=$1
    local fixture_id=$2
    local round=$3
    local directory stdout_path stderr_path timing_path perf_path
    local wall_ns wall_s user_s sys_s peak_rss_kb
    directory=$work_root/$engine
    stdout_path=$result_dir/$engine-$fixture_id-$round.stdout
    stderr_path=$result_dir/$engine-$fixture_id-$round.stderr
    timing_path=$result_dir/$engine-$fixture_id-$round.time
    perf_path=$result_dir/$engine-$fixture_id-$round.perf
    case "$engine" in
        pratex)
            (
                cd "$directory"
                env "${common_env[@]}" /usr/bin/time \
                    -f '%U\t%S\t%M' -o "$timing_path" \
                    perf stat --no-big-num -x $'\t' -o "$perf_path" \
                    -e duration_time -- taskset -c "$cpu" "$pratex" --quiet \
                    -interaction=batchmode -halt-on-error -no-shell-escape \
                    "-output-comment=$output_comment" -- '&latex' "$fixture_id.tex" \
                    >"$stdout_path" 2>"$stderr_path"
            )
            ;;
        uplatex)
            (
                cd "$directory"
                env "${common_env[@]}" /usr/bin/time \
                    -f '%U\t%S\t%M' -o "$timing_path" \
                    perf stat --no-big-num -x $'\t' -o "$perf_path" \
                    -e duration_time -- taskset -c "$cpu" "$uplatex" \
                    -interaction=batchmode -halt-on-error -no-shell-escape \
                    "-output-comment=$output_comment" "$fixture_id.tex" \
                    >"$stdout_path" 2>"$stderr_path"
            )
            ;;
        lualatex)
            (
                cd "$directory"
                env "${lua_env[@]}" /usr/bin/time \
                    -f '%U\t%S\t%M' -o "$timing_path" \
                    perf stat --no-big-num -x $'\t' -o "$perf_path" \
                    -e duration_time -- taskset -c "$cpu" "$lualatex" \
                    --output-format=dvi --interaction=batchmode --halt-on-error \
                    --no-shell-escape "--output-comment=$output_comment" "$fixture_id.tex" \
                    >"$stdout_path" 2>"$stderr_path"
            )
            ;;
        *)
            printf 'unknown engine: %s\n' "$engine" >&2
            exit 1
            ;;
    esac
    wall_ns=$(awk -F '\t' '$3 == "duration_time" { print $1; exit }' "$perf_path")
    case "$wall_ns" in
        '' | *[!0-9]*)
            printf 'perf did not report duration_time for %s %s (%s): %s\n' \
                "$engine" "$fixture_id" "$round" "$wall_ns" >&2
            exit 1
            ;;
    esac
    wall_s=$(awk -v nanoseconds="$wall_ns" 'BEGIN { printf "%.9f", nanoseconds / 1000000000 }')
    IFS=$'\t' read -r user_s sys_s peak_rss_kb <"$timing_path"
    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
        "$engine" "$fixture_id" "$round" "$wall_ns" "$wall_s" \
        "$user_s" "$sys_s" "$peak_rss_kb" >>"$result_dir/runs.tsv"
    local dvi=$directory/$fixture_id.dvi
    test -s "$dvi" || {
        printf '%s did not produce DVI for %s (%s)\n' "$engine" "$fixture_id" "$round" >&2
        exit 1
    }
    printf '%s\t%s\t%s\t%s\t%s\n' \
        "$engine" "$fixture_id" "$round" \
        "$(sha256sum "$dvi" | awk '{print $1}')" \
        "$(wc -c <"$dvi")" >>"$result_dir/dvi.tsv"
    local support_path support_name
    for support_name in aux toc; do
        support_path=$directory/$fixture_id.$support_name
        if test -f "$support_path"; then
            printf '%s\t%s\t%s\t%s\t%s\t%s\n' \
                "$engine" "$fixture_id" "$round" "$support_name" \
                "$(sha256sum "$support_path" | awk '{print $1}')" \
                "$(wc -c <"$support_path")" >>"$result_dir/support-files.tsv"
        fi
    done
}

warmup_round=1
while test "$warmup_round" -le "$warmups"; do
    for fixture_id in "${fixture_ids[@]}"; do
        run_engine pratex "$fixture_id" "warmup-$warmup_round"
        run_engine uplatex "$fixture_id" "warmup-$warmup_round"
        run_engine lualatex "$fixture_id" "warmup-$warmup_round"
    done
    warmup_round=$((warmup_round + 1))
done

run_in_rotated_order() {
    local fixture_id=$1
    local round=$2
    local -a engines
    case $(((round - 1) % 6)) in
        0) engines=(pratex uplatex lualatex) ;;
        1) engines=(uplatex lualatex pratex) ;;
        2) engines=(lualatex pratex uplatex) ;;
        3) engines=(pratex lualatex uplatex) ;;
        4) engines=(lualatex uplatex pratex) ;;
        5) engines=(uplatex pratex lualatex) ;;
    esac
    for engine in "${engines[@]}"; do
        run_engine "$engine" "$fixture_id" "$round"
    done
}

round=1
while test "$round" -le "$runs"; do
    for fixture_id in "${fixture_ids[@]}"; do
        run_in_rotated_order "$fixture_id" "$round"
    done
    round=$((round + 1))
done

for fixture_id in "${fixture_ids[@]}"; do
    for engine in pratex uplatex lualatex; do
        unique_hashes=$(awk -F '\t' -v e="$engine" -v f="$fixture_id" \
            '$1 == e && $2 == f && $3 !~ /^warmup-/ {print $4}' "$result_dir/dvi.tsv" | sort -u | wc -l)
        test "$unique_hashes" -eq 1 || {
            printf '%s DVI changed across measured %s runs\n' "$engine" "$fixture_id" >&2
            exit 1
        }
    done
    pratex_hash=$(awk -F '\t' -v f="$fixture_id" \
        '$1 == "pratex" && $2 == f && $3 !~ /^warmup-/ {print $4; exit}' "$result_dir/dvi.tsv")
    uplatex_hash=$(awk -F '\t' -v f="$fixture_id" \
        '$1 == "uplatex" && $2 == f && $3 !~ /^warmup-/ {print $4; exit}' "$result_dir/dvi.tsv")
    if test "$pratex_hash" = "$uplatex_hash"; then
        printf '%s\tbyte-identical\t%s\n' "$fixture_id" "$pratex_hash" \
            >>"$result_dir/dvi-meaning.tsv"
    else
        "$repo_root/tools/compare-dvi-semantics.py" \
            "$pratex_dir/$fixture_id.dvi" "$uplatex_dir/$fixture_id.dvi" \
            >"$result_dir/$fixture_id-dvi-meaning.txt" || {
            printf 'PraTeX/upLaTeX DVI meaning differs for %s: %s != %s\n' \
                "$fixture_id" "$pratex_hash" "$uplatex_hash" >&2
            exit 1
        }
        printf '%s\tcanonical-match\t%s\n' "$fixture_id" \
            "$(sha256sum "$result_dir/$fixture_id-dvi-meaning.txt" | awk '{print $1}')" \
            >>"$result_dir/dvi-meaning.tsv"
    fi
done

{
    printf 'key\tvalue\n'
    printf 'pratex_sha256\t%s\n' "$(sha256sum "$pratex" | awk '{print $1}')"
    printf 'pratex_format_sha256\t%s\n' "$(sha256sum "$pratex_dir/latex.fmt" | awk '{print $1}')"
    printf 'pratex_format_bytes\t%s\n' "$(wc -c <"$pratex_dir/latex.fmt")"
    printf 'uplatex_binary\t%s\n' "$uplatex"
    printf 'uplatex_resolved_binary\t%s\n' "$uplatex_resolved"
    printf 'uplatex_sha256\t%s\n' "$(sha256sum "$uplatex_resolved" | awk '{print $1}')"
    printf 'lualatex_binary\t%s\n' "$lualatex"
    printf 'lualatex_resolved_binary\t%s\n' "$lualatex_resolved"
    printf 'lualatex_sha256\t%s\n' "$(sha256sum "$lualatex_resolved" | awk '{print $1}')"
    printf 'texmf_root\t%s\n' "$texmf_root"
    printf 'source_date_epoch\t%s\n' "$source_date_epoch"
    printf 'cpu\t%s\n' "$cpu"
    printf 'warmups\t%s\n' "$warmups"
    printf 'runs\t%s\n' "$runs"
    printf 'output_comment\t%s\n' "$output_comment"
    printf 'wall_clock\tperf-duration_time-nanoseconds\n'
    for fixture_id in "${fixture_ids[@]}"; do
        printf 'fixture_%s_sha256\t%s\n' "$fixture_id" \
            "$(sha256sum "$pratex_dir/$fixture_id.tex" | awk '{print $1}')"
        grep 'Output written on' "$pratex_dir/$fixture_id.log" | tail -n 1 | \
            awk -v id="$fixture_id" '{printf "fixture_%s_output\t%s\n", id, $0}'
    done
} >"$result_dir/provenance.tsv"

sha256sum "$result_dir/runs.tsv" "$result_dir/dvi.tsv" "$result_dir/support-files.tsv" \
    "$result_dir/dvi-meaning.tsv" "$result_dir/provenance.tsv" \
    >"$result_dir/artifact-sha256.txt"
printf 'document benchmark passed; PraTeX/upLaTeX DVI meaning matches\n'
printf 'raw artifacts retained at: %s\n' "$result_dir"
